### ISSUE TITLE
Is there some communication with uutils/coreutils ?

### ISSUE THREAD

**Issue by allan-simon** [redox-os/coreutils#42]
as their github project https://github.com/uutils/coreutils state to provide a crossplateform implementation, i wanted to know if there was some cooperation between this project and theirs ?

**Comment by Ticki** [comment]
There haven't really been any communication. The reason we chose to write our own was mainly due to:

1. Platform dependency. `uutils` relies a lot on provided functionalty from libstd, many of which we do not have, yet. Sincee, coreutils are something we cannot let libstd porting block.

2. Minimalism. `uutils` have chosen to resemble a GNU like utility collection, whereas we aim towards a much more minimal one, which is more BSD-like. Look at [this](https://github.com/uutils/coreutils/tree/master/src): there are many utilities, which, in our opinion, is not fitting for a core utility collection, simply due to their usecase being too small. For this exact reason we aim towards a clear seperation between important and less important utilities.

**Comment by allan-simon** [comment]
ok, fair enough, thanks for the clarification

**Comment by Ticki** [comment]
I will close this now. For future questions, refer to [our forum](https://discourse.redox-os.org/) or #redox on irc.mozilla.org.

Thanks!
