### ISSUE TITLE
how to write unit tests for coreutils tools?

### ISSUE THREAD

**Issue by Jeeppler** [redox-os/coreutils#59]
how to write unit tests for coreutils tools? In which place and how?

**Comment by ticki** [comment]
Check out [the testing section in the Rust book](https://doc.rust-lang.org/book/testing.html).

**Comment by Jeeppler** [comment]
@ticki: that is helpful, but if I would like to write unit tests. E. g. for ls where should I put those tests?
Do you have an example unit test in the redox-os repositories?

**Comment by ticki** [comment]
The kernel is a bit of an exception, since that uses a custom testing system. Other repositories can make use of one similar to cargo. [Ralloc has tests in the `test/` directory](https://github.com/redox-os/ralloc/tree/master/tests), [libextra has tests in modules](https://github.com/redox-os/libextra/tree/master/src), [binutils has tested organized as functions side-by-side with the rest of the crate](https://github.com/redox-os/binutils/tree/master/src).

I guess `test/` is most fitting for coreutils, since there is little to nothing to test "internally", the real behavior shall be observed external, thus integration testing is more fitting (i.e., `process::Command` and then some assertions about the output).

**Comment by DaanHoogland** [comment]
referened from the wiki, this is more documentation then an issue
